// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Planner.Db.Context;

#nullable disable

namespace Planner.Db.Migrations
{
    [DbContext(typeof(PlannerDbContext))]
    partial class PlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Planner.Db.Models.Attendee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttendeeGroupId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttendeeGroupId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("Planner.Db.Models.AttendeeGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AttendeeGroups");
                });

            modelBuilder.Entity("Planner.Db.Models.Seat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttendeeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatPosition")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttendeeId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Planner.Db.Models.Attendee", b =>
                {
                    b.HasOne("Planner.Db.Models.AttendeeGroup", null)
                        .WithMany("Attendees")
                        .HasForeignKey("AttendeeGroupId");
                });

            modelBuilder.Entity("Planner.Db.Models.Seat", b =>
                {
                    b.HasOne("Planner.Db.Models.Attendee", null)
                        .WithMany("Seats")
                        .HasForeignKey("AttendeeId");
                });

            modelBuilder.Entity("Planner.Db.Models.Attendee", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Planner.Db.Models.AttendeeGroup", b =>
                {
                    b.Navigation("Attendees");
                });
#pragma warning restore 612, 618
        }
    }
}
